### ISSUE TITLE
MON February 15th @ 6:00pm

### ISSUE THREAD

**Issue by gwmccull** [beerjs/tahoe#28]
Presention on ReactJS, Redux, and High Order Components

**Comment by jordanpapaleo** [comment]
So I was going to present on Parse as I have been getting pretty comfortable with it lately...  Buuuut since they are closing and abandoning 600,000 apps maybe ill just figure out something else.

Someone was crazy enough to give me 5 engineers (@denismorozov, @Landrito, @mhenares, @s-gogna, @wesleykepke) today and I bet I can convince them to talk about what I have them working on.  Stay Posted.  

There may be a little something extra for those who do show up other than the great beer.

![image](https://cloud.githubusercontent.com/assets/1728807/12693912/5551e33e-c6cf-11e5-9f4f-38ee1f32ed55.png)

**Comment by gwmccull** [comment]
Are you trying to get your interns to do your work, already?

That sounds like an interesting topic.

**Comment by jlevine22** [comment]
How about a presentation on migrating away from Parse!

**Comment by jordanpapaleo** [comment]
Some of the guys at EB are going to self host a Parse server

**Comment by jordanpapaleo** [comment]
I will be presenting on ReactJS, Redux, and High Order Components in that context.

**Comment by jordanpapaleo** [comment]
Here is the repo for tomorrow night for those who are interested: https://github.com/jordanpapaleo/redux-forecast
